#pragma once
#include "ClearCmd.hpp"
#include "HistoryCmd.hpp"
#include "LoadCmd.hpp"
#include "QuitCmd.hpp"
#include "RedoCmd.hpp"
#include "SaveCmd.hpp"
#include "ShowCmd.hpp"
#include "UndoCmd.hpp"